motorcontrol:
  ros__parameters:
    pwm:
      forward:
        left:
          min: 187
          max: 500
        right:
          min: 245
          max: 500
      backward:
        left:
          min: 170
          max: 500
        right:
          min: 230
          max: 500
    listenpwmmsg: false
    port: atmegaslave
    useslave: false
    base_frame: "base_footprint"
